### ISSUE TITLE
kickout holes should hide the ball sprite while activated

### ISSUE THREAD

**Issue by Fyda** [Zereijin/GMTK2023#41] opened 2023-07-08 20:00 UTC
currently, the ball sprite stays in place over the kickout hole.

kickout_hole_with_ball.png is intended to show the ball sunken into the hole for the duration of the effect, so the ball sprite should be hidden while that is happening

**Comment by Hawk777** [comment] 2023-07-08 20:24
Duplicate of GH-40.

**Closed as completed by Hawk777** 2023-07-08 20:24 UTC
Labels: enhancement, visual
